### ISSUE TITLE
can't connect to database, can't read PostgreSQL version

### ISSUE THREAD

**Issue by prem-prakash** [elixir-ecto/postgrex#370]
```
SELECT version();
                                                              version
-----------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 10.2 (Ubuntu 10.2-1.pgdg14.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4, 64-bit
(1 row)
```

```
SHOW server_version;
          server_version
----------------------------------
 10.2 (Ubuntu 10.2-1.pgdg14.04+1)
(1 row)
```

```
SHOW server_version_num;
 server_version_num
--------------------
 100002
(1 row)
```

Ecto output
```
[error] GenServer #PID<0.2336.0> terminating
** (RuntimeError) Connect raised a ArgumentError error. The exception details are hidden, as
they may contain sensitive data such as database credentials.

    (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
    (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
    (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
    (postgrex) lib/postgrex/protocol.ex:663: Postgrex.Protocol.bootstrap_send/6
    (postgrex) lib/postgrex/protocol.ex:497: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
```

**Comment by michalmuskala** [comment]
Please update your postgrex version. This bug is fixed in the latest release.

`mix deps.update postrgex` should fix the issue.

**Comment by mendokusai** [comment]
I'm also getting this error did `heroku mix deps.update postgrex` and didn't get a nice clean resolve. Here's my stacktrace upon running `heroku mix ecto.migrate`:
```
10:35:53.426 [error] GenServer #PID<0.240.0> terminating
** (ArgumentError) argument error
    (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
    (postgrex) lib/postgrex/protocol.ex:641: Postgrex.Protocol.bootstrap_send/6
    (postgrex) lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
Last message: nil
** (exit) exited in: :gen_server.call(#PID<0.228.0>, {:checkout, #Reference<0.4183540155.3214409735.223856>, true, :infinity}, 5000)
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
            (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
            (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
            (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
            (postgrex) lib/postgrex/protocol.ex:641: Postgrex.Protocol.bootstrap_send/6
            (postgrex) lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2
            (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
            (connection) lib/connection.ex:622: Connection.enter_connect/5
    (db_connection) lib/db_connection/poolboy.ex:112: DBConnection.Poolboy.checkout/3
    (db_connection) lib/db_connection.ex:920: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:742: DBConnection.run/3
    (db_connection) lib/db_connection.ex:1133: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:584: DBConnection.prepare_execute/4
    (ecto) lib/ecto/adapters/postgres/connection.ex:86: Ecto.Adapters.Postgres.Connection.execute/4
    (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:198: Ecto.Adapters.SQL.query!/5
```

**Comment by ericmj** [comment]
@mendokusai you need to do a new push a new version to heroku. `heroku run` runs on one-off dynos that are not persisted so the postgrex update is immediately thrown away.

**Comment by mendokusai** [comment]
@ericmj I made sure to do that, unfortunately, still not chooching along.
```
heroku run mix deps -h | grep postgrex
> * postgrex 0.13.3 (Hex package) (mix)
  locked at 0.13.3 (postgrex) c277cfb2
```

migrate still returns the same error though, I did note this difference at the end:
```
** (stop) exited in: :gen_server.call(#PID<0.228.0>, {:checkout, #Reference<0.2112337105.277348353.34032>, true, :infinity}, 5000)
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
            (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
            (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
            (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
            (postgrex) lib/postgrex/protocol.ex:641: Postgrex.Protocol.bootstrap_send/6
            (postgrex) lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2
            (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
            (connection) lib/connection.ex:622: Connection.enter_connect/5
Last message: {:EXIT, #PID<0.74.0>, {{:badarg, [{Postgrex.Utils, :"-parse_version/1-fun-0-", 1, [file: 'lib/postgrex/utils.ex', line: 67]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1255]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1255]}, {Postgrex.Utils, :parse_version, 1, [file: 'lib/postgrex/utils.ex', line: 67]}, {Postgrex.Protocol, :bootstrap_send, 6, [file: 'lib/postgrex/protocol.ex', line: 641]}, {Postgrex.Protocol, :handshake, 2, [file: 'lib/postgrex/protocol.ex', line: 475]}, {DBConnection.Connection, :connect, 2, [file: 'lib/db_connection/connection.ex', line: 134]}, {Connection, :enter_connect, 5, [file: 'lib/connection.ex', line: 622]}]}, {:gen_server, :call, [#PID<0.228.0>, {:checkout, #Reference<0.2112337105.277348353.34032>, true, :infinity}, 5000]}}}
```

**Comment by ericmj** [comment]
@mendokusai You have not updated your application running on heroku to use the latest version of postgrex. After running `mix deps.update postgrex` you have to commit your mix.lock and push the commit to the git heroku remote.

**Comment by mendokusai** [comment]
@ericmj I knew I was missing something. Adding `mix.lock` (and updating to `0.13.5`) and then migrating did the trick 👌
